### ISSUE TITLE
Have you tried the RetinaFace

### ISSUE THREAD

**Issue by anguoyang** [njvisionpower/mxnet-cpp-insightface#11]
Hi @njvisionpower , thank you for the great contribution, have you tried RetinaFace to improve the accuracy of insightface? there is also cpp version of RetinaFace: https://github.com/Charrin/RetinaFace-Cpp

**Comment by njvisionpower** [comment]
I have tested several months ago, retinaface got good result but the speed is relatively slow. I'll try implement retinaface version once I'm free. Thanks.
