### ISSUE TITLE
关于这个MTCNN检测时间??

### ISSUE THREAD

**Issue by zzxaijs** [njvisionpower/mxnet-cpp-insightface#13]
为什么在我CPU i7 8750上，只允许mtcnn.Detect 需要的耗时0.2~0.3s,和您的20~30ms,有很大的出入，是不是我的libmxnet 没有编译您说的那个MKL，MKL-DNN或者openblas加速？

**Comment by zzxaijs** [comment]
大神可以理理我吗？

**Comment by njvisionpower** [comment]
Hi，你实测的速度能达到多少？那几个加速的确实是有一定的速度提升的；另外要注意的是检测时间依赖很多东西，比如输入图像的大小和最小人脸的size；另外，多阶段检测网络如果人脸多的话也会比较慢，因为PNet喂给后面的RNet后Onet的个数也会增加，带来不小的开销。

**Comment by zzxaijs** [comment]
我想知道您那边，一张人脸MTCNN 检测需要多久，我自己测试上需要70ms,640*480,没有修改您设置的参数，谢谢大佬回我。

**Comment by njvisionpower** [comment]
我在我的机器测了一下，稳定下来之后检测+抽取特征比对消耗30ms左右，I5-8400 CPU，2.8G主频。你的70ms看起来太慢了，即使python版本的也比这快多了，你是用摄像头测试的吗？初始几帧CPU要预热，多跑几帧试试。

**Comment by zzxaijs** [comment]
好哦，谢谢哥，我去排查一下问题。发送自我的三星盖乐世智能手机。
-------- 原始信息 --------发件人： njvisionpower <notifications@github.com> 日期: 2019/8/12  21:41  (GMT+08:00) 收件人： njvisionpower/mxnet-insightface-cpp <mxnet-insightface-cpp@noreply.github.com> 抄送： zzxaijs <18811381053@163.com>, Author <author@noreply.github.com> 主题： Re: [njvisionpower/mxnet-insightface-cpp] 关于这个MTCNN检测时间?? (#13) 我在我的机器测了一下，稳定下来之后检测+抽取特征比对消耗30ms左右，I5-8400 CPU，2.8G主频。你的70ms看起来太慢了，即使python版本的也比这快多了，你是用摄像头测试的吗？初始几帧CPU要预热，多跑几帧试试。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/njvisionpower/mxnet-insightface-cpp/issues/13?email_source=notifications\u0026email_token=AMFTMHCO7VHIGFCBED3GELDQEFR7FA5CNFSM4IKKO5V2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4CR57I#issuecomment-520429309",

"url": "https://github.com/njvisionpower/mxnet-insightface-cpp/issues/13?email_source=notifications\u0026email_token=AMFTMHCO7VHIGFCBED3GELDQEFR7FA5CNFSM4IKKO5V2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4CR57I#issuecomment-520429309",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
