### ISSUE TITLE
A small mistake I found in `extractFeature()`

### ISSUE THREAD

**Issue by pigoil** [njvisionpower/mxnet-cpp-insightface#14]
Hello! Thank for your excellent work, it helps me a lot. However, I actually found a small typo in this work, resulting some mistakes in my platform: vs2019+opencv3.4.6. When run `test_make_label()` under `Debug` mode, it always generate wrong data in `features.xml` . After dubugging I finally found the bug:

The problem is L143 in [`feature_extract.hpp`](https://github.com/njvisionpower/mxnet-insightface-cpp/blob/01bfbcac90a55993c3018e6ad8b93975aa57dba3/src/feature_extract.hpp#L143), a nameless object `cv::Mat()` is initialized by an `std::vector` object. By default, `cv::Mat(std::vector)` would simply copy the data ptr of  `feature`, so they are just sharing data.

After that, `cv::Mat output` would take the data ptr by **move assignment**`operator=(&&)`, from that nameless object and finally return. And when the function quit, `feature` will delete that ptr and erase those data for some reason under debug mode. So that's the point: `output` and `feature` are sharing the same data ptr, which means the caller of `extractFeature()` can not get a `cv::Mat` object with valid data ptr.

Solution for this problem is change L143 to
````
cv::Mat output = cv::Mat(feature, true).reshape(1, 1);
                                  ^^^^
````
`true` means copy data from the vector instead of sharing the same data ptr.

**Comment by njvisionpower** [comment]
Thanks a lot for your comment, now I have commit the fix. As you said the value "cv::Mat output = cv::Mat(feature, true).reshape(1, 1);" should copy instead of sharing with the same patch when return in function. Actually there‘s already other guys found this issue in #8. Thanks for your detail description.
