### ISSUE TITLE
features.xml的data数据怎么和cv::Mat打印出来的不一致呢

### ISSUE THREAD

**Issue by JiaoPaner** [njvisionpower/mxnet-cpp-insightface#15]
1.利用ptr取出提取的特征值第一个元素值
cv::Mat features = recognizer.extractFeature(aligned_faces[i]);
double value = features.ptr<double>(0)[0];

2.将feature存到xml文件中
cv::FileStorage fs("../features.xml", cv::FileStorage::WRITE);
fs << "features" << features;
fs.release();

比较发现 value和features.xml中data数据的第一个值并不相等 请问是怎么回事

**Comment by JiaoPaner** [comment]
将cv::Mat 转成std::vector后就一致了 但是为什么用opencv访问mat 打印出的值不对呢 是我操作不对吗

**Comment by njvisionpower** [comment]
可能和相关的issue有关 #8  #14 ，extract这一行[代码](https://github.com/njvisionpower/mxnet-insightface-cpp/blob/13213eb1b3491526ac252c244e07dce4031e725b/src/feature_extract.hpp#L146)返回的对象可能有问题，试试返回对象的拷贝。
