### ISSUE TITLE
how to use 512 model ?

### ISSUE THREAD

**Issue by MyraBaba** [njvisionpower/mxnet-cpp-insightface#6]
Hi ,

How we can use insightface 512 model instead of the 128 mobile model ? 

When I change it to 512 model it stops:

MXPredSetInput(pred_feature, "data", input.data(), input.size());
MXPredForward(pred_feature);

**Comment by njvisionpower** [comment]
I think no obvious difference with 512 mobile model, just make make_label also generated 512 dim feature. If there's exception when use MXNet, you can call MXGetLastError() before exception to print the cause of error.
