### ISSUE TITLE
how to  compare two images only ?

### ISSUE THREAD

**Issue by MyraBaba** [njvisionpower/mxnet-cpp-insightface#7]
Hi,

How to compare two person phot and get the distance . ?

I try to extract feature for each photo with :
`cv::Mat recognition(MxNetMtcnn& mtcnn, Mxnet_extract& extract, cv::Mat& img)
`

return the features.

And compare with classify. 

always ı got  same result for all face compares: 

distance : : 3.40282e+38

..

What is the easiest way to do this ?

Best

**Comment by njvisionpower** [comment]
If only compare two feature vector, you can easily get Euclidean distance with opencv norm function. Current codes will compare input face feature with every feature which had been extracted from labeled face, "classify" function do broadcast to make matrix computation faster than loop.


`class_info classify(const cv::Mat& img, const  cv::Mat& cmp)
{
	int rows = cmp.rows;
	cv::Mat broad;
        cv::repeat(img, rows, 1, broad);     // broadcast to make dim same

	broad = broad - cmp;
	cv::pow(broad,2,broad);
	cv::reduce(broad, broad, 1, CV_REDUCE_SUM);    //get all the distance with input img

	double dis;
	cv::Point point;
	cv::minMaxLoc(broad, &dis, 0, &point, 0);   //do sort

	return class_info{dis, point.y};
}`

**Comment by MyraBaba** [comment]
Hi @njvisionpower 
I tested above code and looks give wrong result . I attached two face for merkel. 

for these two distance : 3.40282e+38 look not correct.

tested other photos and also gives same distance ?

![Angela_Merkel_0002](https://user-images.githubusercontent.com/17505439/64617795-bccd7b80-d3e7-11e9-9db0-959962efbafe.jpg)
![Angela_Merkel_0001](https://user-images.githubusercontent.com/17505439/64617796-bd661200-d3e7-11e9-96cf-d708994bc5cc.jpg)

**Comment by MyraBaba** [comment]
@njvisionpower 

I fixed the problem. I re-type and its working now.

these two images distance is now : 0.68221316
