### ISSUE TITLE
Threshold and return list

### ISSUE THREAD

**Issue by MyraBaba** [njvisionpower/mxnet-cpp-insightface#9]
Hi,

1 - How can I change recognition threshold value ? 

2 - How can I get top 10 similar sorted independent from the threshold.

**Comment by njvisionpower** [comment]
Hi,
1. Plz try change value 1.05 of "if(result.min_distance < 1.05)" in function recognition.
2. You can change codes in classify, use cv::sort instead of cv::minMaxLoc.
